netbird: update
changes from https://github.com/NixOS/nixpkgs/commit/d5bb5259e4ea86ab1e472dc4d1bcf897d0f6fba8

otherwise getting following error:
  ERRO client/internal/connect.go:164: error while starting Netbird Connection Engine: socket.Socket for ipv4 failed with: &{%!r(string=socket) %!r(syscall.Errno=1)}awSock

Signed-off-by: Krzysztof Nazarewski <gpg@kdn.im>