rollback flake update due to libreoffice failure
/build/libreoffice-7.3.6.2/sdext/source/pdfimport/xpdfwrapper/pdfioutdev_gpl.cxx:682:23: error: no matching function for call to 'GfxState::getLineDash(double**, int*, double*)'

Signed-off-by: Krzysztof Nazarewski <3494992+nazarewk@users.noreply.github.com>